# Generated by Django 5.1 on 2024-08-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(choices=[('LZQ', 'LZQ'), ('MZQ', 'MZQ'), ('UZQ', 'UZQ')], max_length=3)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
