# Generated by Django 5.1 on 2024-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_quiz_parentattempt_choice_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentregistration',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
