# Generated by Django 5.1 on 2024-08-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_parentattempt_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentattempt',
            name='score',
        ),
        migrations.AddField(
            model_name='parentregistration',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
